// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterProject.Models;

namespace WaterProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20220215165216_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("WaterProject.Models.Project", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectFunctionalityStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectImpact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectPhase")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRegionalProgram")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 842,
                            ProjectName = "Saint Paul's Roman Catholic Primary School",
                            ProjectPhase = "In Service - Feb 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 2,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 150,
                            ProjectName = "Lungi, Tintafor, St.Augustine Secondary School Gate",
                            ProjectPhase = "In Service -Feb 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 3,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 175,
                            ProjectName = "Shikutse B Community, Musava Spring",
                            ProjectPhase = "In Service -Feb 2022",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Protected Spring"
                        },
                        new
                        {
                            MovieId = 4,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 493,
                            ProjectName = "Esokone Primary School",
                            ProjectPhase = "In Service -Feb 2022",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 5,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 1317,
                            ProjectName = "Muroni Primary School",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Rainwater Catchment"
                        },
                        new
                        {
                            MovieId = 6,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 600,
                            ProjectName = "Kamasondo, Raka Village",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 7,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 176,
                            ProjectName = "Kaffu Bullom, Kasongha OIC Vocational School",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 8,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 1100,
                            ProjectName = "Kingsway Secondary School",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 9,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 450,
                            ProjectName = "SLMC Primary School",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 10,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 664,
                            ProjectName = "Lungi, Gbaneh Bana, Next to Mosque",
                            ProjectPhase = "In Service -Jan 2022",
                            ProjectRegionalProgram = "Port Loko, Sierra Leone WaSH Program",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 11,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 5000,
                            ProjectName = "Lema Community A Sand Dam",
                            ProjectPhase = "In Service -Dec 2021",
                            ProjectRegionalProgram = "Southeastern Kenya WaSH Program",
                            ProjectType = "Sand Dam"
                        },
                        new
                        {
                            MovieId = 12,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 500,
                            ProjectName = "Taureg Refugee Camp, Burkina Faso",
                            ProjectPhase = "In Service - Jan 2015",
                            ProjectRegionalProgram = "Wells for Burkina Faso",
                            ProjectType = "Well Rehab"
                        },
                        new
                        {
                            MovieId = 13,
                            ProjectFunctionalityStatus = "",
                            ProjectImpact = 0,
                            ProjectName = "St.Catherine Lema Girls School",
                            ProjectPhase = "Estimated Install Date: 05 / 28 / 2022",
                            ProjectRegionalProgram = "Southeastern Kenya WaSH Program",
                            ProjectType = "Rainwater Catchment"
                        },
                        new
                        {
                            MovieId = 14,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 314,
                            ProjectName = "Kavyuni Salvation Army Primary School",
                            ProjectPhase = "In Service -May 2020",
                            ProjectRegionalProgram = "Southeastern Kenya WaSH Program",
                            ProjectType = "Rainwater Catchment"
                        },
                        new
                        {
                            MovieId = 15,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 500,
                            ProjectName = "Nyeaba Community",
                            ProjectPhase = "Initial Installation: Aug 2013",
                            ProjectRegionalProgram = "Wells for South Sudan -NeverThirst",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 16,
                            ProjectFunctionalityStatus = "Functional",
                            ProjectImpact = 500,
                            ProjectName = "Teresia Primary School Water Project",
                            ProjectPhase = "In Service - Oct 2012",
                            ProjectRegionalProgram = "Wells for Kenya",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 17,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 500,
                            ProjectName = "House of Hope Orphanage Well",
                            ProjectPhase = "Initial Installation: Aug 2011",
                            ProjectRegionalProgram = "Deep Wells -Kenya",
                            ProjectType = "Borehole Well and Submersible Pump"
                        },
                        new
                        {
                            MovieId = 18,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 300,
                            ProjectName = "Kakiriing Community Well",
                            ProjectPhase = "Initial Installation: Mar 2011",
                            ProjectRegionalProgram = "Wells for Kenya",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 19,
                            ProjectFunctionalityStatus = "Low / No Water or Mechanical Breakdown",
                            ProjectImpact = 155,
                            ProjectName = "St.Stephen Eshihaka Secondary School",
                            ProjectPhase = "In Service -Jan 2017",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Rainwater Catchment"
                        },
                        new
                        {
                            MovieId = 20,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 500,
                            ProjectName = "Musenyi Community Well",
                            ProjectPhase = "Initial Installation: Nov 2011",
                            ProjectRegionalProgram = "Wells for Rwanda",
                            ProjectType = "Borehole Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 21,
                            ProjectFunctionalityStatus = "Under Community Care",
                            ProjectImpact = 300,
                            ProjectName = "Vouregane Community",
                            ProjectPhase = "Initial Installation: Jan 2014",
                            ProjectRegionalProgram = "Wells for Burkina Faso",
                            ProjectType = "Well Rehab"
                        },
                        new
                        {
                            MovieId = 22,
                            ProjectFunctionalityStatus = "Under Community Care",
                            ProjectImpact = 250,
                            ProjectName = "Soussoubro Community",
                            ProjectPhase = "Initial Installation: Aug 2014",
                            ProjectRegionalProgram = "Wells for Burkina Faso",
                            ProjectType = "Well Rehab"
                        },
                        new
                        {
                            MovieId = 23,
                            ProjectFunctionalityStatus = "Community Managed",
                            ProjectImpact = 500,
                            ProjectName = "Kikoko Community Well",
                            ProjectPhase = "Initial Installation: Apr 2012",
                            ProjectRegionalProgram = "Wells for Masindi / Jinga Uganda",
                            ProjectType = "Dug Well and Hand Pump"
                        },
                        new
                        {
                            MovieId = 24,
                            ProjectFunctionalityStatus = "Water Flowing -Needs Attention",
                            ProjectImpact = 315,
                            ProjectName = "Chegulo Community, Werabunuka Spring",
                            ProjectPhase = "In Service -Nov 2018",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Protected Spring"
                        },
                        new
                        {
                            MovieId = 25,
                            ProjectFunctionalityStatus = "Low / No Water or Mechanical Breakdown",
                            ProjectImpact = 500,
                            ProjectName = "Khabukoshe Primary School",
                            ProjectPhase = "In Service -Apr 2019",
                            ProjectRegionalProgram = "Western Kenya WaSH Program",
                            ProjectType = "Rainwater Catchment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
